### ISSUE TITLE
Add format checking

### ISSUE THREAD

**Issue by sublimator** [ripple/ripple-binary-codec#10]
The primary client of this module is RippleAPI which checks/enforces its own schema, however it would still be useful to add per TransactionType format checking to `encodeForSigning` and `encodeForMultiSigning`

**Comment by intelliot** [comment]
Should we just `throw` if the format check fails?

**Comment by sublimator** [comment]
I would

**Comment by sublimator** [comment]
I think @wilsonianb might be using it for validator manifests, which have no TransactionType/LedgerEntryType so keep that in mind.

**Comment by sublimator** [comment]
So probably you could get away with full format checking if LedgerEntryType/TransactionType field is in the object, $somehow detect a validator manifest and handle accordingly, otherwise require at least one serialized field (https://github.com/ripple/ripple-binary-codec/blob/master/src/enums/definitions.json#L40)

**Comment by intelliot** [comment]
Replaced by https://github.com/XRPLF/xrpl.js/issues/1807
