### ISSUE TITLE
Problem with X-Address encoding/serialization

### ISSUE THREAD

**Issue by mrosendin** [ripple/ripple-binary-codec#116]
I kept getting this error message when calling RippleAPI's `sign()` method:

`version bytes do not match any of the provided version`

I did some debugging and tracked it down to the (X-Address?) serialization:
https://github.com/ripple/ripple-binary-codec/blob/master/src/binary.ts#L69

I signed a testnet transaction with a classic address successfully.

**Comment by natenichols** [comment]
I'm seeing this error occur when trying to encode X-Addresses in issued currencies. This should be fixed in #113. 

Does that sound consistent with what you were seeing @mrosendin?

**Comment by intelliot** [comment]
I don't think RippleAPI's `sign()` method can accept an X-address directly. Typically, you would convert the X-address prior to signing; for example, this is done automatically by `prepareTransaction`.

**Comment by natenichols** [comment]
Is there a related issue in ripple-api?

**Comment by mrosendin** [comment]
Yes @natenichols, that sounds right to me. I was using `prepareTransaction` for an issued currency payment when I saw this.
