### ISSUE TITLE
Duplicate FieldID: ValidatorToDisable and ValidatorToReEnable

### ISSUE THREAD

**Issue by corverroos** [ripple/ripple-binary-codec#127]
As per documentation at https://github.com/ripple/ripple-binary-codec/tree/master/src/enums:

_Sort code numbers are reused for fields of different types, but different fields of the same type never have the same sort code. When you combine the type code with the sort code, you get the field's unique Field ID._

The source definition of both `ValidatorToDisable` and `ValidatorToReEnable` have a `nth:20` and `type: Blob`
```
[
      "ValidatorToDisable",
      {
        "nth": 20,
        "isVLEncoded": true,
        "isSerialized": true,
        "isSigningField": true,
        "type": "Blob"
      }
    ],
    [
      "ValidatorToReEnable",
      {
        "nth": 20,
        "isVLEncoded": true,
        "isSerialized": true,
        "isSigningField": true,
        "type": "Blob"
      }
    ],
    ```

**Comment by natenichols** [comment]
@corverroos Thanks for opening this issue!

This change is up in PR #130 if you want to have a look.
