### ISSUE TITLE
Some objects can not be encoded, resulting in "not valid hex" error.

### ISSUE THREAD

**Issue by nixer89** [ripple/ripple-binary-codec#132]
I am using: "ripple-binary-codec": "^1.1.2",

I am currently trying to "encode" some ledger_data objects from rippled. There are a **many** objects which can not be encoded. The error is:

[2021-06-08 19:58:17] [LOG]    Error: 283 is not a valid hex-string
    at Function.UInt64.from (..\node_modules\ripple-binary-codec\dist\types\uint-64.js:60:23)
    at ..\node_modules\ripple-binary-codec\dist\types\st-object.js:129:56
    at Array.forEach (<anonymous>)
    at Function.STObject.from (..\node_modules\ripple-binary-codec\dist\types\st-object.js:128:16)
    at serializeObject (..\node_modules\ripple-binary-codec\dist\binary.js:59:32)
    at Object.encode (..\node_modules\ripple-binary-codec\dist\index.js:24:12)

The above example occurs when encoding following ledger object:

```
{
  Balance: { currency: 'GCB', issuer: 'rrrrrrrrrrrrrrrrrrrrBZbvji', value: '0' },
  Flags: 2162688,
  HighLimit: {
    currency: 'GCB',
    issuer: 'rBfVgTnsdh8ckC19RM8aVGNuMZnpwrMP6n',
    value: '0'
  },
  HighNode: '283',
  LedgerEntryType: 'RippleState',
  LowLimit: {
    currency: 'GCB',
    issuer: 'rhRFGCy2RJTA8oxkjjtYTvofPVGqcgvXWj',
    value: '2000000'
  },
  LowNode: '0',
  PreviousTxnID: 'C0C37CE200B509E0A529880634F7841A9EF4CB65F03C12E6004CFAD9718D6694',
  PreviousTxnLgrSeq: 24695242,
  index: '0000041EFD027808D3F78C8352F97E324CB816318E00B977C74ECDDC7CD975B2'
}
```

There are many more objects which can actually not be encoded - mostly (a lot!) RippleState and DirectoryNode objects.
In the above example, the "HighNode" value seems to be the culprit. (same for LowNode in other objects).

An example for an error encoding a DirectoryNode is:

```
{
  Flags: 0,
  IndexPrevious: '2',
  Indexes: [
    'A3454ACED87177146EABD5E4A256021D836D1E3617618B1EB362D10B0D1BAC6A',
    'E1ED9E8D280BBE0B6656748FD647231851C6C650794D5E6852DFA1E35E68630F'
  ],
  LedgerEntryType: 'DirectoryNode',
  Owner: 'rHzDaMNybxQppiE3uWyt2N265KvAKdiRdP',
  RootIndex: '0CB3C1AD2C371136AEA434246D971C5FCCD32CBF520667E131AB7B10D706E752',
  index: '0B4A2E68C111F7E42FAEEE405F7344560C8240840B151D9D04131EB79D080167'
}
```

**Comment by natenichols** [comment]
hi @nixer89, thanks for opening an issue!

You're absolutely correct, it looks like `HighNode` is the issue.
 
What is the `ledger_index` (or `ledger_hash`) of your `ledger_data` request?

**Comment by nixer89** [comment]
I think the above examples are from ledger index 64130309.
But I believe they are not created in that ledger but just included as ledger entries.

I was gathering those entries using the "ledger_data" websocket command of the latest, validated ledger.

**Comment by natenichols** [comment]
Gotcha, found it. I'm writing up and testing a fix, looks like its a hex parsing issue.

For the time being a `ledger_data` WebSocket command w/ the `binary` flag set to `true` should accomplish essentially the same thing.

Something like gets the encoded info directly from `rippled`: 
```json
{
  "id": "fetches ledger entries as a hex string",
  "ledger_index": "64130309",
  "command": "ledger_data",
  "limit": 10,
  "binary": true
}
```

Let me know if that does what you're trying to do. Hoping to have a fix out for `ripple-binary-codec` shortly. Thanks again for opening an issue!

**Comment by intelliot** [comment]
@natenichols is this related to https://github.com/ripple/ripple-binary-codec/pull/121 ?

**Comment by intelliot** [comment]
@nixer89 Just curious, what's the use case for this? i.e. When/why do you want to ledger_data objects from rippled?

**Comment by nixer89** [comment]
@intelliot: I am providing an API which scans an "full ledger" to provide data on XRPL tokens and (under development) ledger data analysis.

I use the token API in my own project: https://xumm.community/tokens

![grafik](https://user-images.githubusercontent.com/25486793/121294866-63f98280-c8ee-11eb-81ba-0fff8931ca30.png)

That is why I implemented it in the first place. But at the moment it is still growing to provide more data. As example some "full ledger statistics":

![grafik](https://user-images.githubusercontent.com/25486793/121296117-6957cc80-c8f0-11eb-9aa0-55b99bf36eee.png)

But this is an unfinished project yet :)

**Comment by nixer89** [comment]
I just ran my code again with the version:

"ripple-binary-codec": "^1.1.3-beta.0",

and get the following error:

Error: 19a5 is not a valid hex-string
    at Function.UInt64.from (..\node_modules\ripple-binary-codec\dist\types\uint-64.js:57:23)
    at ..\node_modules\ripple-binary-codec\dist\types\st-object.js:129:56
    at Array.forEach (<anonymous>)
    at Function.STObject.from (..\node_modules\ripple-binary-codec\dist\types\st-object.js:128:16)
    at serializeObject (..\node_modules\ripple-binary-codec\dist\binary.js:59:32)
    at Object.encode (..\node_modules\ripple-binary-codec\dist\index.js:24:12)

I believe the Regex only accepts upper case characters:

var HEX_REGEX = /^[A-F0-9]{1,16}$/;

and the check for "19a5" fails therefore?

**Comment by natenichols** [comment]
Hi @nixer89, nice catch.

Published another beta that adjusts that `HEX_REGEX`.

Would you mind giving it a try:
```
yarn add ripple-binary-codec@1.1.3-beta.1
```

**Comment by nixer89** [comment]
Hi @natenichols,

looks good now! I didn't got any error anymore in my tests. Thank you!

Best,
Daniel
