### ISSUE TITLE
lodash needs updating to version 4.17.13

### ISSUE THREAD

**Issue by vogelito** [ripple/ripple-binary-codec#29]
Please see this: https://snyk.io/blog/snyk-research-team-discovers-severe-prototype-pollution-security-vulnerabilities-affecting-all-versions-of-lodash/

Vulnerable versions: < 4.17.13
Patched version: 4.17.13

https://github.com/ripple/ripple-binary-codec/blob/487bda5aed231fdfef17d71c003a314f2aeeafb0/package.json#L20

**Comment by intelliot** [comment]
Thanks, this is fixed in the next release.
