### ISSUE TITLE
Expand node version compatibility

### ISSUE THREAD

**Issue by intelliot** [ripple/ripple-binary-codec#32]
package.json currently specifies `"node": ">=10.0.0 <11.0.0"`. Look into supporting more versions of node, particularly versions 11 and 12.

**Comment by swansontec** [comment]
Agreed.

The commit that restricted the version range is https://github.com/ripple/ripple-binary-codec/commit/4eb1f7d6361def8162d2ffc73e8478452d63f96e. This commit mentions the unit tests failing, which indeed they do.

Looking at the unit tests, they are doing things like `assert.deepEquals(someUint8Array, [0, 1])`. Of course this won't work - a regular `Array` and a `Uint8Array` are different types. So, the unit tests simply need to be updated to compare things of the correct type, and the problems will go away.

**Comment by swansontec** [comment]
I have just submitted PR #33 to address this.

**Comment by intelliot** [comment]
Fixed by https://github.com/ripple/ripple-binary-codec/pull/33

Released in [0.2.3](https://github.com/ripple/ripple-binary-codec/releases/tag/0.2.3)
